### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by achaiah** [Eromera/erfnet_pytorch#15]
Hi,

Would you be able to add license to your code so others may use your work?

Thanks

**Comment by Eromera** [comment]
Hi, the readme contained already the license (Creative Commons Attribution-NonCommercial 4.0 International License) but I have added to the repos a "license.txt" containing the full text. Thanks a lot for the message!

**Comment by achaiah** [comment]
Ok thanks. Any chance you could use a more liberal license such as MIT or Apache 2.0?

**Comment by Eromera** [comment]
Sorry, at the moment we can only stick to the current license. We are studying other licenses but at the moment Creative NonCommercial is the one that best complies with our university requirements. If we decide to change it I'll let you know!
