### ISSUE TITLE
reimplement help

### ISSUE THREAD

**Issue by Zerahhah** [Eromera/erfnet_pytorch#21]
Our work is almost done, and we are ready to quote your paper. But we encountered difficulties in reproduction.
Can I ask a question, how long have you spent training the model?

**Comment by Eromera** [comment]
Hi! Sorry for the late reply. Depends on your GPU and how many epochs you set but it just takes a few hours (less than half a day) for a decoder training with 90 epochs in a decent GPU like Titan X.
