### ISSUE TITLE
how to test a pic?

### ISSUE THREAD

**Issue by GuideWsp** [Eromera/erfnet_pytorch#25]
when i use the code in the eval folder to test a pictures from VOC2012, i got some wrong results and every time, i got different results. i wonder if there are some trick you uncoment. if you can provide a demo in this github. thanks.

**Comment by Eromera** [comment]
Hi! Sorry for the late reply. Sorry but I haven't tested the code in Pascal VOC 2012, but it should run correctly with the codes in the eval folder like "eval_cityscapes_color.py", maybe with some slight modifications like the number of classes. Can you provide more details on how you are getting wrong results?

**Comment by GuideWsp** [comment]
thanks for your reply. i hava found y. my code hava a bug.
