### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by InstantWindy** [Eromera/erfnet_pytorch#27]
Has anyone run this code? How does it work

**Comment by Eromera** [comment]
Hi! You can check the READMEs in each folder for some tips on how to use each code for training or evaluation. If you have more doubts after that just ask!

**Comment by InstantWindy** [comment]
Can you tell me how to test the mean iou in the cityscape test set online? Because the cityscape test set has no tags, online testing is required, but I don't know what to do. Thank you very much！

**Comment by Eromera** [comment]
Hi. You need to use the "eval/eval_cityscapes_server.py" script with "--subset test" option which will produce the segmentation output for the 500 test images. Then you need to compress these images in a single ZIP and upload in their [webpage ](https://www.cityscapes-dataset.com/submit/), which is the only way to get the result in the test set.

**Comment by InstantWindy** [comment]
It can directly obtain the test mean iou？Only uploading the test prediction images in their webpage? Thank you!
