### ISSUE TITLE
Results not reproducible

### ISSUE THREAD

**Issue by tkasarla** [Eromera/erfnet_pytorch#33]
Have run the training at 1/4th resolution. 

Two different runs give wildly different IoUs on the val set.

1st time: 65.43
2nd time: 60.28

Setting torch.manual_seed also doesn't work.

**Comment by Eromera** [comment]
Hi @tkasarla, Iou on 1/4th of resolution are normally quite bad since the model is optimized for 1/2 resolution (1024x512). The results should be reproducible at that resolution but I cannot guarantee good result in others.
