### ISSUE TITLE
Turns out to 5 fps on GTX1080TI, far way from realtime

### ISSUE THREAD

**Issue by lucasjinreal** [Eromera/erfnet_pytorch#37]
I have test on GTX1080ti with ENet, its runs about 19 fps, however ERFNet just got 5 fps on gtx1080ti

![image](https://user-images.githubusercontent.com/21303438/49707200-4f789880-fc65-11e8-8329-a4e0ebee5466.png)

**Comment by amiltonwong** [comment]
Whats resolution for the input are you using?

**Comment by lucasjinreal** [comment]
Input is (512, 1024)

**Comment by Eromera** [comment]
Hi, can you make sure its running on gpu and using full load by displaying nvidia-smi?

**Comment by phdsky** [comment]
I tested on 1080ti with input (512, 1024) got almost 50fps.  Thanks for @Eromera's great job!

**Comment by Eromera** [comment]
@phdsky Thanks, im glad it works!
