### ISSUE TITLE
Image Normalization in Pre-processing for Cityscapes

### ISSUE THREAD

**Issue by kmul00** [Eromera/erfnet_pytorch#39]
Hi,

I was trying to train the network on the Cityscapes dataset, and while going through the main [training script](https://github.com/Eromera/erfnet_pytorch/blob/master/train/main.py), I could not find any **Image Normalization** code in the pre-processing part ([here](https://github.com/Eromera/erfnet_pytorch/blob/master/train/main.py#L38-L71)).

Does that mean we don't train the network on normalized image or am I missing something?

Thanks in advance!

**Comment by Eromera** [comment]
Hi, yes you are right in the main code there is no normalization but in my own code i sometimes use it, you can add it in MyCoTransform function. Cheers

**Comment by kmul00** [comment]
Thank you!
