### ISSUE TITLE
How to compute class weight

### ISSUE THREAD

**Issue by ywlng** [Eromera/erfnet_pytorch#41]
In (https://github.com/Eromera/erfnet_pytorch/blob/master/train/main.py#L92-L131), you give different weights for every class when calculating loss.  Can you introduce the method you compute this weights. I want to use that in other datasets. Thanks.

**Comment by Eromera** [comment]
Hi, you can check [the Torch code where this is calculated](https://github.com/Eromera/erfnet/blob/master/train/data/loadCityscapeList.lua), below the "calculate histClasses and mean/std of the dataset, or load from previous calculations"

**Comment by ywlng** [comment]
ok, thanks

**Comment by charlotte12l** [comment]
@Eromera Now your code is invisible, can you introduce the method you compute this weight? Or share the code to me? (I contacted you via email several days before ...but no response yet)
