### ISSUE TITLE
Difference between the calculation of encoder weights and the decoder weights

### ISSUE THREAD

**Issue by razvanbarbura** [Eromera/erfnet_pytorch#48]
hi, @Eromera
I want to train your model with a different dataset and different classes.

What is the difference between the calculation of encoder weights and the decoder weights?

I read in your article that you are using the next formula to determine the weights:

![image](https://user-images.githubusercontent.com/58234537/78386840-f9acca00-75e6-11ea-9c93-2cde9d5cddb4.png)

I saw that you have different values for the encoder and decoder weights:

![image](https://user-images.githubusercontent.com/58234537/78388192-41ccec00-75e9-11ea-8ec3-1e64cec89972.png)

If I use this formula to calculate the encoder weights, what should I do in order to calculate the decoder weights? Is there a connection between the encoder weights and the decoder weights? A multiplication factor or something ?

**Comment by Eromera** [comment]
hi @razvanbarbura, the weights for decoder are calculated based on the frequency of the pixels of the dataset at 1024x512 resolution and the weights for encoder are based on the dataset with this resolution downscaled by 8 (128x64). This downscaling changes some shapes, which causes the difference in pixel frequencies from decoder to encoder.

**Comment by razvanbarbura** [comment]
@Eromera  thank you for your answer. I have one more question. When I calculate the histogram for dataset I have to compute the histogram for every image individually, get the probability for each class in image and then i will make an average on all the images in the dataset to get the final probabilities, or I have to compute the histogram for all images once and then get the probabilities ?
